version: '3.1'

services:

  api:
    image: api:v3
    ports:
      - "8090:8090"
    restart: unless-stopped
    depends_on:
      - mongo
    networks:
      - backend

  mongo:
    image: mongo
    restart: always
    ports:
      - "27017:27017"
    networks:
      - backend
    command: "--bind_ip_all"

networks:
  backend:
